Update

diff --git a/lib/brew b/lib/brew
--- a/lib/brew
+++ b/lib/brew
@@ -9,6 +9,12 @@ run_brew() {
         brew update
         [[ $? ]] && e_success "Done"
 
+        e_header "Adding third-party repositories..."
+        # Add the third-party repositories required for install
+        brew tap homebrew/cask-fonts # font-jetbrains-mono
+        brew tap weaveworks/tap # eksctl
+        [[ $? ]] && e_success "Done"
+
         e_header "Updating any existing Homebrew formulae..."
         # Upgrade any already-installed formulae
         brew upgrade
@@ -19,14 +25,33 @@ run_brew() {
         local -a missing_formulae
         local -a desired_formulae=(
             'awscli'
-            'bash'
-            'bash-completion'
-            'coreutils'
+            'bat'
+            'eksctl'
+            'exa'
+            'fish'
+            'gh'
             'git'
+            'gnupg'
             'httpie'
             'jq'
-            'node'
-            'tree'
+            'kubectl'
+            'linkerd'
+            'minikube'
+            'tmux'
+        )
+
+        local list_cask
+        local -a missing_cask
+        local -a desired_cask=(
+            'alacritty'
+            'bloomrpc'
+            'docker'
+	        'font-jetbrains-mono'
+            'google-chrome'
+            'insomnia'
+            'slack'
+            'tunnelblick'
+	        'visual-studio-code'
         )
 
         for index in ${!desired_formulae[*]}
@@ -37,6 +62,14 @@ run_brew() {
             fi
         done
 
+        for index in ${!desired_cask[*]}
+        do
+            if ! cask_exists ${desired_cask[$index]}; then
+                # Store the name (and options) of every missing formula
+                missing_cask=("${missing_cask[@]}" "${desired_cask[$index]}")
+            fi
+        done
+
         if [[ "$missing_formulae" ]]; then
             # Convert the array of missing formula into a list of space-separate strings
             list_formulae=$( printf "%s " "${missing_formulae[@]}" )
@@ -44,6 +77,17 @@ run_brew() {
             e_header "Installing missing Homebrew formulae..."
             # Install all missing formulae
             brew install $list_formulae
+
+            [[ $? ]] && e_success "Done"
+        fi
+
+        if [[ "$missing_cask" ]]; then
+            # Convert the array of missing formula into a list of space-separate strings
+            list_cask=$( printf "%s " "${missing_cask[@]}" )
+
+            e_header "Installing missing Homebrew cask..."
+            # Install all missing cask
+            brew cask install $list_cask
 
             [[ $? ]] && e_success "Done"
         fi
